// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';


const SUPABASE_URL = "https://luunspijrwbrirzibiii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1dW5zcGlqcndicmlyemliaWlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1ODMwNzQsImV4cCI6MjA3MzE1OTA3NH0.asozYwXZrFe1702x48Nvb0SQ00GKfQvyeGNSUYJf8FA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});